### ISSUE TITLE
Atribute Error

### ISSUE THREAD

**Issue by FND98** [courtarro/fakeTube#3]
Hello! I am writing to you because when I try to run the server that you created, it opens and closes the server window down but when I check it with IDLE 3.0, it gives me the following error.
Traceback (most recent call last):
  File "C:\Users\usernameHere\Desktop\fakeTube-master\server.py", line 8, in <module>
    with socketserver.TCPServer(("", PORT), handler) as httpd:
AttributeError: 'TCPServer' object has no attribute '__exit__'

Is it my fault or maybe there is an issue in the code? I downloaded the master and didn't touch anything, did all the steps and it gives me that error

**Comment by courtarro** [comment]
I believe this is due to you running Python older than 3.6. Apparently the ability to use `socketserver.TCPServer` inside a `with` block was added in Python 3.6. If you're in Python 3.5 and can't upgrade, try this instead:

Change lines 8-10 to:

    httpd = socketserver.TCPServer(("", PORT), handler)
    print("Serving at port: " + str(PORT))
    httpd.serve_forever()
